#!/bin/bash

# @env-config-doc * tool: getpassword - securely pass sensitive data via command arguments

function usage {
	echo "Reads without echo first line of the input and prints it to the standard output."
	echo "Use to pass sensitive information (passwords) via command arguments."
	echo ""
	echo "Example:"
	echo "\$ svn commit -m \"Bugfix\" --username user --password \$(getpassword)"
	echo "# Enter password from keyboard (no echo will be shown on screen)"
	exit 1
}

if [[ 0 < $# ]]; then
	usage
fi

read -s password
echo ${password}
