#!/bin/bash

# @env-config-doc * tool: getpassword - securely pass sensitive data via command arguments

function print_usage {
	echo "Usage:"
	echo "    -h          - print help"
	echo "    -p <prompt> - use specified prompt"
	echo""
	echo "Example:"
	echo "\$ svn commit -m \"Bugfix\" --username user --password \$(getpassword)"
	echo "# Enter password from keyboard (no echo will be shown on screen)"
	exit 1
}

function print_help {
	echo "Reads without echo first line of the input and prints it to the standard output."
	echo "Use to pass sensitive information (passwords) via command arguments."
	echo ""
	print_usage
}

prompt="Password: "
while getopts ":hp:" OPT; do
	case "${OPT}" in
		h) print_help;;
		p) prompt="${OPTARG}";;
		\?) echo "Error: invalid option -${OPTARG}"; print_usage;;
		:) echo "Error: option -${OPTARG} requires an argument"; print_usage;;
	esac
done
if [[ $(( $# + 1 )) > ${OPTIND} ]]; then
	echo "Error: invalid argument \"${!OPTIND}\""
	print_usage
fi

read -p "${prompt}" -s password
echo ${password}
