#ENV_CONFIG_DIR=<path>
#ENV_CONFIG_PLATFORM=(darwin|linux)
#ENV_CONFIG_COLORS=(yes|no)

echo " /\_/\ "
echo "( o.o )"
echo " > ^ < "

if [[ ${ENV_CONFIG_COLORS} == 'yes' ]]; then
	if [[ ${ENV_CONFIG_PLATFORM} == 'darwin' ]]; then
		alias ls="ls -G"
		alias grep="grep --color=auto"
	fi
fi
